version: "3.8"
services:
  app:
    build:
      context: .
      args:
        - API_BASE_URL=${API_BASE_URL}
        - CLIENT_ID=$CLIENT_ID
        - LOGIN_CLIENT_ID=$LOGIN_CLIENT_ID
        - CLIENT_SECRET=$CLIENT_SECRET
        - GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    driver: bridge
    name: ${DEFAULT_NETWORK_NAME:-opex}