version: "3.8"
services:
  web-app:
    image: ghcr.io/opexdev/web-app
    environment:
      - ENV=$WEB_APP_ENV
      - API_BASE_URL=$API_BASE_URL
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    driver: bridge