name: Deploy OPEX-Web-APP - Demo
on:
  push:
    branches:
      - main
jobs:
  jenkinsJob:
    name: Deploy OPEX-Web-APP new demo version
    runs-on: ubuntu-latest
    steps:
      - name: Trigger opex-web-app-demo on Jenkins
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "opex-web-app-demo"
